from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

from src.app.contracts.renderer import ReportRenderer
from src.domain.models.report import Report
from src.domain.models.widgets import AlertWidget, ChartWidget, KpiCard, TableWidget, TextBlockWidget, Widget

from .chart_serializer import ChartSerializer


_DEFAULT_TEMPLATES = {
    "base.html": """
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ report.metadata.title }}</title>
    <style>
      body { font-family: Arial, sans-serif; margin: 0; padding: 0; color: #1f2937; background: #f8fafc; }
      .container { max-width: 1280px; margin: 0 auto; padding: 24px; }
      .page-header { margin-bottom: 32px; }
      .meta { color: #6b7280; margin-top: 8px; }
      .alerts { display: grid; gap: 12px; margin: 16px 0 24px; }
      .alert { background: #fff7ed; border: 1px solid #fdba74; border-radius: 12px; padding: 16px; }
      .section { margin: 32px 0; }
      .section-header { margin-bottom: 16px; }
      .widgets { display: grid; gap: 16px; }
      .cards { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 16px; }
      .card, .widget-box { background: white; border-radius: 14px; padding: 16px; box-shadow: 0 2px 10px rgba(15, 23, 42, 0.05); }
      .card h3, .widget-box h3 { margin: 0 0 8px; font-size: 14px; color: #6b7280; }
      .card-value { font-size: 28px; font-weight: bold; }
      table { width: 100%; border-collapse: collapse; }
      th, td { text-align: left; padding: 10px 12px; border-bottom: 1px solid #e5e7eb; vertical-align: top; }
      th { background: #f8fafc; font-size: 13px; color: #475569; }
      .chart-payload { background: #0f172a; color: #e2e8f0; border-radius: 10px; padding: 12px; overflow-x: auto; font-size: 12px; }
      .muted { color: #64748b; font-size: 13px; }
      .footer { margin: 48px 0 12px; color: #64748b; font-size: 13px; }
    </style>
  </head>
  <body>
    <div class="container">
      <header class="page-header">
        <h1>{{ report.metadata.title }}</h1>
        {% if report.metadata.subtitle %}<p>{{ report.metadata.subtitle }}</p>{% endif %}
        <div class="meta">
          Table: <strong>{{ report.metadata.table_qualified_name }}</strong>
          {% if report.metadata.row_count is not none %} · Rows: <strong>{{ report.metadata.row_count }}</strong>{% endif %}
          {% if report.metadata.execution_duration_ms is not none %} · Execution: <strong>{{ report.metadata.execution_duration_ms }} ms</strong>{% endif %}
          · Generated at: <strong>{{ report.metadata.generated_at }}</strong>
        </div>
      </header>

      {% if report.global_alerts %}
      <section class="alerts">
        {% for alert in report.global_alerts %}
          {{ render_widget(alert) }}
        {% endfor %}
      </section>
      {% endif %}

      {% for section in report.sorted_sections %}
      <section class="section">
        <div class="section-header">
          <h2>{{ section.title }}</h2>
          {% if section.subtitle %}<p class="muted">{{ section.subtitle }}</p>{% endif %}
        </div>
        {% if section.alerts %}
        <div class="alerts">
          {% for alert in section.alerts %}
            {{ render_widget(alert) }}
          {% endfor %}
        </div>
        {% endif %}
        {% set kpi_cards = [] %}
        {% set other_widgets = [] %}
        {% for widget in section.widgets %}
          {% if widget.__class__.__name__ == 'KpiCard' %}
            {% set _ = kpi_cards.append(widget) %}
          {% else %}
            {% set _ = other_widgets.append(widget) %}
          {% endif %}
        {% endfor %}
        {% if kpi_cards %}
        <div class="cards">
          {% for widget in kpi_cards %}
            {{ render_widget(widget) }}
          {% endfor %}
        </div>
        {% endif %}
        {% if other_widgets %}
        <div class="widgets" style="margin-top: 16px;">
          {% for widget in other_widgets %}
            {{ render_widget(widget) }}
          {% endfor %}
        </div>
        {% endif %}
      </section>
      {% endfor %}

      <footer class="footer">Generated by the PostgreSQL dashboard report pipeline.</footer>
    </div>
  </body>
</html>
"""
}


@dataclass(slots=True)
class JinjaReportRenderer(ReportRenderer):
    """Jinja2-based HTML renderer with embedded fallback templates."""

    template_dir: str | Path | None = None
    base_template_name: str = "base.html"
    chart_serializer: ChartSerializer = field(default_factory=ChartSerializer)

    def __post_init__(self) -> None:
        try:
            from jinja2 import ChoiceLoader, DictLoader, Environment, FileSystemLoader, select_autoescape
        except ModuleNotFoundError as exc:
            raise ModuleNotFoundError(
                "Jinja2 is required to use JinjaReportRenderer. Install it with `pip install jinja2`."
            ) from exc

        loaders: list[Any] = []
        if self.template_dir is not None:
            loaders.append(FileSystemLoader(str(self.template_dir)))
        loaders.append(DictLoader(_DEFAULT_TEMPLATES))
        self._environment = Environment(
            loader=ChoiceLoader(loaders),
            autoescape=select_autoescape(enabled_extensions=("html", "xml"), default_for_string=True),
            trim_blocks=True,
            lstrip_blocks=True,
        )
        self._environment.globals["render_widget"] = self._render_widget

    def render(self, report: Report) -> str:
        template = self._environment.get_template(self.base_template_name)
        return template.render(report=report)

    def _render_widget(self, widget: Widget) -> str:
        if isinstance(widget, KpiCard):
            help_text_html = f'<div class="muted">{widget.help_text}</div>' if widget.help_text else ""
            return (
                f'<article class="card"><h3>{widget.title}</h3>'
                f'<div class="card-value">{widget.value}</div>'
                f'{help_text_html}</article>'
            )
        if isinstance(widget, AlertWidget):
            details = "".join(f"<li>{detail}</li>" for detail in widget.details)
            details_html = f"<ul>{details}</ul>" if details else ""
            return (
                f'<article class="alert"><strong>{widget.title}</strong>'
                f'<p>{widget.message}</p>{details_html}</article>'
            )
        if isinstance(widget, TableWidget):
            head = "".join(f"<th>{column}</th>" for column in widget.columns)
            body = "".join(
                "<tr>" + "".join(f"<td>{value}</td>" for value in row) + "</tr>"
                for row in widget.rows
            )
            subtitle = f'<p class="muted">{widget.subtitle}</p>' if widget.subtitle else ""
            return (
                f'<article class="widget-box"><h3>{widget.title}</h3>{subtitle}'
                f'<table><thead><tr>{head}</tr></thead><tbody>{body}</tbody></table></article>'
            )
        if isinstance(widget, ChartWidget):
            subtitle = f'<p class="muted">{widget.subtitle}</p>' if widget.subtitle else ""
            payload = self.chart_serializer.serialize(widget)
            return (
                f'<article class="widget-box"><h3>{widget.title}</h3>{subtitle}'
                f'<pre class="chart-payload">{payload}</pre></article>'
            )
        if isinstance(widget, TextBlockWidget):
            subtitle = f'<p class="muted">{widget.subtitle}</p>' if widget.subtitle else ""
            return f'<article class="widget-box"><h3>{widget.title}</h3>{subtitle}<p>{widget.body}</p></article>'
        raise TypeError(f"Unsupported widget type: {type(widget)!r}")
